name: build
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
    - main
    
jobs:
  bulid:
    name: build docker
    runs-on: ubuntu-22.04

    steps:
        - uses: actions/checkout@v4
        - uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_PASS }}
        - run: |
            IMAGE_TAG=itreema130/c-app:$GITHUB_SHA
            docker build . -t $IMAGE_TAG
            docker push $IMAGE_TAG
